### ISSUE TITLE
限速了

### ISSUE THREAD

**Issue by zhaowweny** [CodeTips/BaiduNetdiskPlugin-macOS#36]
差不多昨天开始的，只有几十Kb的下载速度。

**Comment by steve7688** [comment]
我也是。16KB。已哭晕在厕所。

**Comment by zhaowweny** [comment]
@steve7688 我刚刚安装了下，我这电信50M带宽，速度能到1.8M/s，还可以了，估计是修复了，不过readme上面作者的7、8M/s简直神速啊
