### ISSUE TITLE
找不到文中所说的路径

### ISSUE THREAD

**Issue by ghost** [CodeTips/BaiduNetdiskPlugin-macOS#48]
点击clone or download下载项目，解压运行libBaiduNetdiskPlugin.xcodeproj，然后Edit Schemes->Executable->Other->选择百度网盘。然后运行工程

![default](https://user-images.githubusercontent.com/37524933/45282039-5d0a6f00-b50c-11e8-8fd1-f713832662ec.png)

**Comment by CodeTips** [comment]
点击 My Mac 前面那个图标，展开后 就看到了。
