### ISSUE TITLE
百度云盘显示SVIP了，但是下载还是限速状态

### ISSUE THREAD

**Issue by samxu1993** [CodeTips/BaiduNetdiskPlugin-macOS#52]
![image](https://user-images.githubusercontent.com/42229811/47128250-11917080-d2c3-11e8-86dc-53742d5d2880.png)
Mac os 10.12.6
百度云盘版本2.2.2
 
已经显示SVIP了，但是下载还是限速状态，更换账户无效，重启电脑也不行

**Comment by CodeTips** [comment]
确实是这样的，可能服务端已经添加了限制。限制唯一可以使用的就是每天的试用两次不限制时长。
