### ISSUE TITLE
这个破解之后速度？？？？

### ISSUE THREAD

**Issue by olafchou** [CodeTips/BaiduNetdiskPlugin-macOS#56]
<img width="973" alt="2018-10-26 07 35 57" src="https://user-images.githubusercontent.com/19890798/47536300-dc53d680-d8f1-11e8-91ad-a4fea44190b1.png">

**Comment by olafchou** [comment]
![snipaste_2018-10-26_09-31-40](https://user-images.githubusercontent.com/19890798/47539312-4a07fe80-d902-11e8-84a5-912c7488fe68.png)
那现在咋办呢？？？这速度只能200？？？

**Comment by CodeTips** [comment]
试用极速下载还是这么高的话，那就是资源热度不够。就算真的开通svip也是这个速度的。

**Comment by yanqinglove** [comment]
不行的 😆

**Comment by yanqinglove** [comment]
老老实实用Aria2吧

**Comment by yanqinglove** [comment]
downloader试一试

**Comment by olafchou** [comment]
> downloader试一试

可以突破百度云下载限制嘛？？？求链接
