### ISSUE TITLE
哪里有“Edit Schemes->Executable->Other”

### ISSUE THREAD

**Issue by zhouhesheng** [CodeTips/BaiduNetdiskPlugin-macOS#9]
哪里有“Edit Schemes->Executable->Other”？

**Comment by CodeTips** [comment]
Xcode

**Comment by liss1990** [comment]
我也想问这个哪里呢？ 左上角哪里？真的没发现啊！

**Comment by CodeTips** [comment]
![screen shot 2018-05-15 at 9 38 22 am](https://user-images.githubusercontent.com/36583116/40031792-d6f7e81a-5823-11e8-9780-34ff69aee308.png)
